spring:
  application:
    name: event-router
  rabbitmq:
    username: admin
    password: password
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings

server:
  port: 8081