apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-prod.yaml convert -o kubeconfig/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: account-manager
  name: account-manager
spec:
  containers:
    - env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-account-manager:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
      image: localhost/account-manager:latest
      livenessProbe:
        exec:
          command:
            - curl
            - -f
            - http://localhost:8082/actuator/health
        failureThreshold: 3
        periodSeconds: 10
        timeoutSeconds: 5
      name: account-manager
      ports:
        - containerPort: 8082
          protocol: TCP
  restartPolicy: OnFailure
