apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-prod.yaml convert -o kubeconfig/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: cloud-gateway-server
  name: cloud-gateway-server
spec:
  ports:
    - name: "8060"
      port: 8060
      targetPort: 8060
  selector:
    io.kompose.service: cloud-gateway-server
