apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-prod.yaml convert -o kubeconfig/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  containers:
    - image: localhost/eureka-server:latest
      livenessProbe:
        exec:
          command:
            - curl
            - -f
            - http://localhost:8761/actuator/health
        failureThreshold: 3
        periodSeconds: 10
        timeoutSeconds: 5
      name: eureka-server
      ports:
        - containerPort: 8761
          protocol: TCP
  restartPolicy: OnFailure
