apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-prod.yaml convert -o kubeconfig/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: event-manager
  name: event-manager
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: event-manager
