spring:
  application:
    name: event-manager
  rabbitmq:
    username: admin
    password: password
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 3
          max-interval: 5m
          multiplier: 2
    event-processing-queue: event-processing
    notification-sending-queue: notification-sending
    identification-processing-queue: identification-processing
    insight-processing-queue: insight-processing
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true